const ENTER_USERNAME = "ENTER_USERNAME";
const ENTER_PASSWORD = "ENTER_PASSWORD";
const SEND_LOGINING = "SEND_LOGINING";
const LOGINING_COMPLETE = "LOGINING_COMPLETE";
const LOGIN_ERROR = "LOGIN_ERROR"

export {
  ENTER_USERNAME,
  ENTER_PASSWORD,
  SEND_LOGINING,
  LOGINING_COMPLETE,
  LOGIN_ERROR
}